add args to treminated Transaction
altera2015/usbserial pull request #87
Opened 2023-08-31 14:38 UTC by EParisot

2023-09-03 17:01 UTC, altera2015 approved these changes

2023-09-03 17:21 UTC, EParisot commented
Ok I think I should do it again but from the new commit after previous PR and rework a bit

2023-09-03 18:40 UTC, EParisot commented
ok this should be better, I added the optional arge on both Transformers also.
Can you re-run the merge ? or should I create another PR ?

2023-09-03 18:54 UTC, altera2015 commented
> ok this should be better, I added the optional arge on both Transformers also. Can you re-run the merge ? or should I create another PR ?

Hmm still failing some flutter checks :(

2023-09-03 19:07 UTC, EParisot commented
Ican assume the semicolumn issues have been introduced by my PR but I don't know about the rest thought, did the PR 77 passed the same tests ?

2023-09-03 19:11 UTC, EParisot commented
Also, I cant manage to make it works with my code, app crash as soon as I plug or unplug my usb device.
SDK 33 seems to have a bug regarding the getParcelableExtra : https://issuetracker.google.com/issues/240585930
I will have to revert to previous version on my fork for now...

2023-09-03 19:12 UTC, altera2015 commented
Not sure what is happening here. The upgrade to dart 3 likely caused these issues. I don't have time to dive in but this article does explain how to get passed them:

https://medium.com/@reginfell/flutter-dart-strong-mode-fd936bb8551f

2023-09-03 19:14 UTC, altera2015 commented
I'll revert the previous MR.

2023-09-03 19:30 UTC, altera2015 commented
I've reverted 77 and fixed the warnings, rebase on master.

2023-09-03 19:35 UTC, EParisot commented
Yes multiple problems I think, I did the same on my fork thanks

2023-09-04 13:50 UTC, EParisot commented
I just fixed the (formating) conflics, this works on my side

2023-09-04 16:10 UTC, altera2015 requested changes
fix some lint warnings

2023-09-04 16:10 UTC, altera2015 commented on lib/transaction.dart
> +      {int maxLen: 1024, bool stripTerminator: true}) {
```suggestion
      {int maxLen = 1024, bool stripTerminator = true}) {
```

2023-09-04 16:10 UTC, altera2015 commented on lib/transaction.dart
> +      {int maxLen: 1024}) {
```suggestion
      {int maxLen = 1024}) {
```

2023-09-04 16:10 UTC, altera2015 commented on lib/transaction.dart
> +      {int maxLen: 1024, bool stripTerminator: true}) {
```suggestion
      {int maxLen = 1024, bool stripTerminator = true}) {
```

2023-09-04 17:22 UTC, EParisot commented
sry about that , I my Java env is not up to date

2023-09-04 20:04 UTC, merged